### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by science-enthusiast** [GPUPeople/faimGraph#1]
Hi
While running SetupScript.py the error shown below occurs. The error seems to go away if BFS related steps are commented out in the CMakeLists.txt file. However, that could affect the functionality of the system. For e.g., the executable mainaimGraph is anyway not created.

Setup CUB

CUB already cloned
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hari/work/faimGraph/build
[ 34%] Built target faimgraph
[ 39%] Built target dynamicVertices
[ 48%] Built target main
[ 48%] Built target STC
[ 53%] Built target spmv
[ 58%] Built target reInitTC
[ 67%] Built target CComp
[ 67%] Built target CCoeff
[ 72%] Built target PR
[ 76%] Built target queryTC
[ 81%] Built target continuousTC
[ 83%] Building CUDA object CMakeFiles/BFS.dir/src/algorithms/BFS.cu.o
[ 88%] Built target BC
[ 93%] Built target concurrentTC
In file included from /usr/local/cuda-11.2/bin/../targets/x86_64-linux/include/cub/util_namespace.cuh:36,
                 from /usr/local/cuda-11.2/bin/../targets/x86_64-linux/include/thrust/system/cuda/config.h:76,
                 from /usr/local/cuda-11.2/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/execution_policy.h:33,
                 from /usr/local/cuda-11.2/bin/../targets/x86_64-linux/include/thrust/iterator/detail/device_system_tag.h:23,
                 from /usr/local/cuda-11.2/bin/../targets/x86_64-linux/include/thrust/iterator/iterator_traits.h:111,
                 from /usr/local/cuda-11.2/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/util.h:31,
                 from /usr/local/cuda-11.2/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/core/alignment.h:21,
                 from /usr/local/cuda-11.2/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/core/triple_chevron_launch.h:30,
                 from /home/hari/work/faimGraph/include/../include/cub/cub/device/dispatch/dispatch_histogram.cuh:49,
                 from /home/hari/work/faimGraph/include/../include/cub/cub/device/device_histogram.cuh:41,
                 from /home/hari/work/faimGraph/include/../include/cub/cub/cub.cuh:52,
                 from /home/hari/work/faimGraph/src/algorithms/BFS.cu:5:
/usr/local/cuda-11.2/bin/../targets/x86_64-linux/include/cub/version.cuh:46: warning: "CUB_VERSION" redefined
   46 | #define CUB_VERSION 101000
      | 
In file included from /home/hari/work/faimGraph/include/../include/cub/cub/util_namespace.cuh:36,
                 from /home/hari/work/faimGraph/include/../include/cub/cub/util_arch.cuh:37,
                 from /home/hari/work/faimGraph/include/../include/cub/cub/config.cuh:35,
                 from /home/hari/work/faimGraph/include/../include/cub/cub/cub.cuh:37,
                 from /home/hari/work/faimGraph/src/algorithms/BFS.cu:5:
/home/hari/work/faimGraph/include/../include/cub/cub/version.cuh:46: note: this is the location of the previous definition
   46 | #define CUB_VERSION 101300
      | 
/usr/local/cuda-11.2/bin/../targets/x86_64-linux/include/cub/util_arch.cuh(159): error: class template "cub::RegBoundScaling" has already been defined

/usr/local/cuda-11.2/bin/../targets/x86_64-linux/include/cub/util_arch.cuh(172): error: class template "cub::MemBoundScaling" has already been defined

/home/hari/work/faimGraph/src/algorithms/BFS.cu(786): warning: integer conversion resulted in a change of sign

/home/hari/work/faimGraph/src/algorithms/BFS.cu(829): warning: integer conversion resulted in a change of sign

/home/hari/work/faimGraph/src/algorithms/BFS.cu(878): warning: integer conversion resulted in a change of sign

/home/hari/work/faimGraph/src/algorithms/BFS.cu(932): warning: integer conversion resulted in a change of sign

2 errors detected in the compilation of "/home/hari/work/faimGraph/src/algorithms/BFS.cu".
make[2]: *** [CMakeFiles/BFS.dir/build.make:76: CMakeFiles/BFS.dir/src/algorithms/BFS.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:264: CMakeFiles/BFS.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Setup faimGraph done

**Comment by delanyinspiron6400** [comment]
Thanks very much, since NVIDIA recently started including CUB automatically with CUDA, the extra setup included here is not necessary and leads to a multiple definition.
Thanks for bringing that to my attention, I'll update that as soon as possible.

**Comment by delanyinspiron6400** [comment]
Updated and should work again with the new CUDA toolkit :smile:

**Comment by science-enthusiast** [comment]
Thanks. The project builds now.
